local database = require('hopcsharp.database')
local history = require('hopcsharp.parse.history')

describe('history', function()
    it('__add_parse_history - happy path', function()
        database.__drop_db()
        history.__add_parse_history_entry('somecommithash')
        local rows = database.__get_db():eval([[ SELECT * FROM parse_history ]])
        assert(#rows == 1)
        assert(rows[1].commit_hash == 'somecommithash')
    end)

    it('__add_parse_history - nil', function()
        database.__drop_db()
        history.__add_parse_history_entry(nil)
        local rows = database.__get_db():eval([[ SELECT * FROM parse_history ]])
        assert(rows)
    end)

    it('__add_parse_history - empty', function()
        database.__drop_db()
        history.__add_parse_history_entry('')
        local rows = database.__get_db():eval([[ SELECT * FROM parse_history ]])
        assert(rows)
    end)

    it('__add_parse_history - happy path', function()
        database.__drop_db()
        history.__add_parse_history_entry('somecommithash')
        local rows = database.__get_db():eval([[ SELECT * FROM parse_history ]])
        assert(#rows == 1)
        assert(rows[1].commit_hash == 'somecommithash')
    end)

    it('__get_last_parsed_commit - no history', function()
        database.__drop_db()
        local commit_hash = history.__get_last_parsed_commit()
        assert(commit_hash == '')
    end)

    it('__get_last_parsed_commit - single entry', function()
        database.__drop_db()
        history.__add_parse_history_entry('1')
        local commit_hash = history.__get_last_parsed_commit()
        assert(commit_hash == '1')
    end)

    it('__get_last_parsed_commit - multiple entries', function()
        database.__drop_db()
        history.__add_parse_history_entry('1')
        history.__add_parse_history_entry('2')
        history.__add_parse_history_entry('3')
        history.__add_parse_history_entry('4')
        history.__add_parse_history_entry('5')
        local commit_hash = history.__get_last_parsed_commit()
        assert(commit_hash == '5')
    end)
end)
