local database = require('hopcsharp.database')
local history = require('hopcsharp.parse.history')

describe('history', function()
    it('__add_parse_history - happy path', function()
        database.__drop_db()
        history.__add_parse_history_entry('somecommithash')
        local rows = database.__get_db():eval([[ SELECT * FROM parse_history ]])
        assert(#rows == 1)
        assert(rows[1].parse_date ~= '')
        assert(rows[1].commit_hash == 'somecommithash')
    end)

    it('__add_parse_history - nil', function()
        database.__drop_db()
        history.__add_parse_history_entry(nil)
        local rows = database.__get_db():eval([[ SELECT * FROM parse_history ]])
        assert(rows)
    end)

    it('__add_parse_history - empty', function()
        database.__drop_db()
        history.__add_parse_history_entry('')
        local rows = database.__get_db():eval([[ SELECT * FROM parse_history ]])
        assert(rows)
    end)

    it('__get_parse_history - 1', function()
        database.__drop_db()
        history.__add_parse_history_entry('one')
        history.__add_parse_history_entry('two')
        history.__add_parse_history_entry('three')
        local rows = history.__get_parse_history()
        assert(#rows == 1)
        assert(rows[1].commit_hash == 'one')
    end)

    it('__get_parse_history - 2', function()
        database.__drop_db()
        history.__add_parse_history_entry('two')
        history.__add_parse_history_entry('three')
        history.__add_parse_history_entry('one')
        local rows = history.__get_parse_history()
        assert(#rows == 1)
        assert(rows[1].commit_hash == 'two')
    end)

    it('__get_parse_history - 3', function()
        database.__drop_db()
        history.__add_parse_history_entry('three')
        history.__add_parse_history_entry('two')
        history.__add_parse_history_entry('one')
        local rows = history.__get_parse_history()
        assert(#rows == 1)
        assert(rows[1].commit_hash == 'three')
    end)
end)

