local utils = require('hopcsharp.hop.providers.utils')
local test_utils = require('test.utils')
local database_utils = require('hopcsharp.database.utils')

describe('hop.providers.utils', function()
    it('__get_node_type - method definition', function()
        test_utils.prepare('test/sources/hop_to_reference.cs', 'test/sources/hop_to_reference.cs', 30, 22)
        local current_word, node_type = utils.__get_node_type(vim.fn.expand('<cword>'), vim.treesitter.get_node())
        assert(current_word == 'AlfaMethod')
        assert(node_type == nil)
    end)

    it('__get_node_type - attribute', function()
        test_utils.prepare('test/sources/hop_to_reference.cs', 'test/sources/hop_to_reference.cs', 5, 10)
        local current_word, node_type = utils.__get_node_type(vim.fn.expand('<cword>'), vim.treesitter.get_node())
        assert(current_word == 'AlfaAttribute')
        assert(node_type == database_utils.types.CLASS)
    end)

    it('__get_node_type - invocation_expression', function()
        test_utils.prepare('test/sources/hop_to_reference.cs', 'test/sources/hop_to_reference.cs', 14, 15)
        local current_word, node_type = utils.__get_node_type(vim.fn.expand('<cword>'), vim.treesitter.get_node())
        assert(current_word == 'Method1')
        assert(node_type == database_utils.types.METHOD)
    end)
end)
